# Relaxed Markdownlint configuration for easier committing
# See: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

# Enable rules selectively (more permissive approach)
default: false

# Ignore specific files
ignore:
  - "CONTRIBUTING.md"
  - "node_modules/"
  - ".github/"

# Enable only essential rules for basic readability
rules:
  # Only enforce critical formatting issues
  MD001: true    # Heading levels should only increment by one level at a time
  MD003: true    # Heading style should be consistent
  MD022: true    # Headings should be surrounded by blank lines
  MD025: true    # Multiple top level headings in the same document

  # Relaxed line length - much longer limit
  MD013:
    line_length: 200  # ↳ very generous limit
    headings: false   # ↳ no limit on headings
    code_blocks: false # ↳ no limit on code blocks
    tables: false     # ↳ no limit on tables

  # Allow flexible list formatting
  MD004: false   # Unordered list style
  MD005: false   # Inconsistent indentation for list items
  MD007: false   # Unordered list indentation
  MD030: false   # Spaces after list markers
  MD032: false   # Lists should be surrounded by blank lines

  # Allow flexible emphasis and links
  MD033: false   # Allow inline HTML
  MD034: false   # Allow bare URLs
  MD036: false   # Allow emphasis used instead of heading
  MD037: false   # Allow spaces inside emphasis markers

  # Allow flexible code formatting
  MD010: false   # Allow hard tabs
  MD014: false   # Allow $ in commands without showing output
  MD031: false   # Allow fenced code blocks without blank lines
  MD040: false   # Allow fenced code blocks without language

  # Allow flexible punctuation and spacing
  MD009: false   # Allow trailing spaces
  MD026: false   # Allow trailing punctuation in headings
  MD027: false   # Allow multiple spaces after blockquote symbol
  MD035: false   # Allow any horizontal rule style

# File-specific overrides - even more relaxed
"README.md":
  MD013: false   # No line length limits

"CONTRIBUTING.md":
  MD013: false   # No line length limits

"docs/**/*.md":
  MD013: false   # No line length limits for documentation
  MD033: false   # Allow any HTML for rich formatting

"*.md":
  MD013: false   # No line length limits by default
