services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: rw_user
      POSTGRES_PASSWORD: rw_pass
      POSTGRES_DB: readwise
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rw_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-reset:
    image: postgres:16
    environment:
      - POSTGRES_USER=rw_user
      - POSTGRES_PASSWORD=rw_pass
      - POSTGRES_DB=readwise
    command: >
      bash -c "
        export PGPASSWORD=rw_pass &&
        dropdb -h db -U rw_user -f readwise &&
        createdb -h db -U rw_user readwise
      "
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    command: uvicorn readwise_vector_db.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
