"""Create initial tables

Revision ID: 6e900a582819
Revises:
Create Date: 2025-06-23 17:48:29.120817

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e900a582819"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table(
        "highlight",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_author", sa.String(), nullable=True),
        sa.Column("source_title", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=True),
        sa.Column("highlighted_at", sa.String(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.HALFVEC(3072), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_highlight_embedding",
        "highlight",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_l2_ops"},
    )
    op.create_table(
        "syncstate",
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("service"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("syncstate")
    op.drop_index("ix_highlight_embedding", table_name="highlight")
    op.drop_table("highlight")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
